services:
  api1:
    build: ./api
    container_name: api1
    ports:
      - "3001:3000"
    environment:
      - MESSAGE=Holiiiiiii
  api2:
    build: ./api
    container_name: api2
    ports:
      - "3002:3000"
    environment:
      - MESSAGE=soy Tamara Caspito

  api3:
    build: ./api
    container_name: api3
    ports:
      - "3003:3000"
    environment:
      - MESSAGE=Fin de las apis

  db:  
    image: postgres:16-alpine
    container_name: lab_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: lab_user
      POSTGRES_PASSWORD: lab_password
      POSTGRES_DB: lab_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
  

volumes:
  db_data:
    driver: local